### ISSUE TITLE
Using both npm and yarn?

### ISSUE THREAD

**Issue by crcastle** [clintonwoo/hackernews-react-graphql#15]
Is there a reason this project is using both npm and yarn?  I think one or the other could be used exclusively (along with its respective lockfile).

If the reason is ¯\_(ツ)_/¯ I'd be happy to submit a PR consolidating to one or the other!

EDIT: Apologies for not explaining where I got the assumptions that both were being used.
- npm: All commands in the README and some commands in `package.json` use `npm`
- yarn: Three commands in `package.json` use `yarn`

**Comment by clintonwoo** [comment]
Hi, thanks for submitting an issue. The project technically uses a Yarn lockfile and docker builds using Yarn so in that regard it uses Yarn for package management. I originally wrote the documentation using NPM so a developer not familiar with Yarn can still use the project until they are ready to look into Yarn.

Perhaps the decision can be made now which to go with. Yarn is ~25% faster and can be configured for offline mode but npm is the default and has caught up in most ways. NPM is probably the better choice for maximum compatibility. What do you say?

**Comment by crcastle** [comment]
If one of the goals of the project are to make it accessible to Node developers of all levels, then I'd suggest going with npm.  And I think you're right that npm has caught up with yarn in most ways (since v5).  If it hadn't then maybe I could see the case for sticking with yarn.

You cool if I make a PR changing everything over to npm (code, docs, lockfile)?

(I also wanted to add a [Deploy to Heroku button](https://devcenter.heroku.com/articles/heroku-button) and suggest a few other changes, but I'll put those in separate PRs.)

**Comment by chongiscool** [comment]
Hi, I just learned React and React Redux, now I am learning React Native, one of my friend suggest having both *npm* and *yarn* installed on my computer can create conflict, and His suggestion is uninstalling one and using the other, Should I uninstall? Thanks!

**Comment by bel7aG** [comment]
you shouldn't.

**Comment by chongiscool** [comment]
@bel7aG thanks for replying.

**Comment by ivanraybuglosa** [comment]
@chongiscool I also doing rails with react-redux and have yarn and npm at the same time.
But i dont understand why we shouldn't remove either one of those? @bel7aG

**Comment by clintonwoo** [comment]
I updated it to only use npm since it's the default. The README.md recommends updating to use yarn or pnpm however
