### ISSUE TITLE
Rebuild project in TypeScript

### ISSUE THREAD

**Issue by clintonwoo** [clintonwoo/hackernews-react-graphql#17]
Hi, just wanted to see what the community's interest would be in seeing this project rebuilt in TypeScript. Obviously this would come with a number of benefits including strong types, better static code analysis and clearer APIs. This would lead to higher developer productivity.

If enough people are interested I can go ahead and do it.

**Comment by dangdennis** [comment]
Interested! Thanks for doing this. I'll consider forking and doing it myself as homework too.

**Comment by MarkPollmann** [comment]
Hi @clintonwoo, are you still interested in doing this? I, and I'm sure many others, would love to help!

**Comment by clintonwoo** [comment]
Ok.. I'm currently working on a TypeScript upgrade! I will convert the whole project to TypeScript since I believe this is the best way to get types in JS and I want it for my own side projects! Types in JS is a no-brainer, it makes developing and scaling code bases to be much easier

**Comment by clintonwoo** [comment]
Hi all, the project is now built in TypeScript! 🎉
