### ISSUE TITLE
Downvoted comments aren't grayed out

### ISSUE THREAD

**Issue by danem** [clintonwoo/hackernews-react-graphql#2]
Your clone doesn't seem to render the comment classes correctly. For example on the real site a comment with .c72 will be rendered on your site as .c00.

**Comment by clintonwoo** [comment]
Thanks for submitting the issue. Yes I believe it is true I've seen it myself but it might be due to HN not exposing comment downvote data in their public API.

If you can double check that and respond or submit a PR, it will be gladly welcome to close the issue!
