### ISSUE TITLE
freeze when docker build --tag 'clintonwoo/hackernews-react-graphql:latest' --rm .

### ISSUE THREAD

**Issue by Johoshua** [clintonwoo/hackernews-react-graphql#30]
it will hang when trying to build docker container. it stops at step "RUN npm run build".  I did some debug, it looks like hangs at "next build" command. any suggestion where to look next?

**command -**
docker build --tag 'clintonwoo/hackernews-react-graphql:latest' --rm .

**docker freeze at here -**

Step 7/17 : RUN npm run build
 ---> Running in daef81749112

> hackernews@0.9.0 build /usr/src/app
> npm run clean && tsc --project tsconfig.server.json && next build

> hackernews@0.9.0 clean /usr/src/app
> rm -rf build/app && rm -rf dist && rm -rf src/.next

Creating an optimized production build ...

> Using external babel configuration
> Location: "/usr/src/app/babel.config.js"
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Compiled successfully.

 ┌ /
 ├ /_app
 ├ /_document
 ├ /_error
 ├ /active
 ├ /ask
 ├ /best
 ├ /bestcomments
 ├ /bookmarklet
 ├ /changepw
 ├ /dmca
 ├ /favorites
 ├ /forgot
 ├ /formatdoc
 ├ /front
 ├ /hidden
 ├ /item
 ├ /jobs
 ├ /leaders
 ├ /lists
 ├ /login
 ├ /newcomments
 ├ /newest
 ├ /newpoll
 ├ /newsfaq
 ├ /newsguidelines
 ├ /newswelcome
 ├ /noobcomments
 ├ /noobstories
 ├ /reply
 ├ /security
 ├ /show
 ├ /showhn
 ├ /shownew
 ├ /submit
 ├ /submitted
 ├ /threads
 ├ /upvoted
 └ /user

**Comment by clintonwoo** [comment]
I've made a massive update to this project and haven't seen this issue. So I will close the issue, please reopen if you see it again
