### ISSUE TITLE
Freeze When  i use this command npm run build && npm start command not working

### ISSUE THREAD

**Issue by asepsisIT** [clintonwoo/hackernews-react-graphql#31]
I have run this command  = npm run build && npm start

But some how npm run build command not working for me. 
Node version : v8.11.4
Npm version : 5.6.0

Freeze : 

Compiled successfully.

 ┌ /
 ├ /_app
 ├ /_document
 ├ /_error
 ├ /active
 ├ /ask
 ├ /best
 ├ /bestcomments
 ├ /bookmarklet
 ├ /changepw
 ├ /dmca
 ├ /favorites
 ├ /forgot
 ├ /formatdoc
 ├ /front
 ├ /hidden
 ├ /item
 ├ /jobs
 ├ /leaders
 ├ /lists
 ├ /login
 ├ /newcomments
 ├ /newest
 ├ /newpoll
 ├ /newsfaq
 ├ /newsguidelines
 ├ /newswelcome
 ├ /noobcomments
 ├ /noobstories
 ├ /reply
 ├ /security
 ├ /show
 ├ /showhn
 ├ /shownew
 ├ /submit
 ├ /submitted
 ├ /threads
 ├ /upvoted
 └ /user

**Comment by clintonwoo** [comment]
I've made a massive update to this project and haven't seen this issue occur. So I will close this issue but you can recreate if you still see it
