### ISSUE TITLE
npm ERR! missing script: dev

### ISSUE THREAD

**Issue by muthyalaDivyaVenkatesh** [clintonwoo/hackernews-react-graphql#33]
i have checked the package.json but i am unable to dev script in it

**Comment by muthyalaDivyaVenkatesh** [comment]
i used npm start it is working but i am wondered why in description it is mentioned to run npm run dev insted of npm start

**Comment by pankaj8blr** [comment]
i also used npm run start  and its working fine.

**Comment by clintonwoo** [comment]
Yes, `npm start` is the new way to run the app for development. `npm run start:prod` is the command for running it in production.

I just updated the README. Thanks
