### ISSUE TITLE
Standardize test location?

### ISSUE THREAD

**Issue by benmccann** [clintonwoo/hackernews-react-graphql#38]
Thanks so much for providing this! It's helpful in learning these technologies

One question I had when looking at the code is that there seem to be different places to put the tests. Sometimes they're in a `__tests__` directory and sometimes they aren't. For example:
* https://github.com/clintonwoo/hackernews-react-graphql/blob/master/src/__tests__/active.spec.tsx
* https://github.com/clintonwoo/hackernews-react-graphql/blob/master/src/components/comment-box.spec.tsx

Is this intended? If so, what goes where?

**Comment by clintonwoo** [comment]
Yeah the `__tests__` folder was placed in that location since NextJS uses every file in the `pages` folder to make a URL route handler. We obviously don't want test files becoming routes on the web server so we have that + all the other unit tests are colocated.
