### ISSUE TITLE
Failed when run test script

### ISSUE THREAD

**Issue by dangleit01** [clintonwoo/hackernews-react-graphql#51]
When I ran command "npm test", I received error: 
```
Pattern: jest.config.js - 0 matches
npm ERR! Test failed.
```
The current test script is described as
```
"test": "jest --config --runInBand jest.config.js"
```

To fix it, I changed the script to:

"test": "jest --config jest.config.js --runInBand"

**Comment by clintonwoo** [comment]
Yes that seems weird, sorry the comment is a bit late but looks like I've fixed it a long time ago also :)
