### ISSUE TITLE
Live Demo Doesn't Work

### ISSUE THREAD

**Issue by SkylarKitchen** [clintonwoo/hackernews-react-graphql#58]
![image](https://user-images.githubusercontent.com/3465616/115813245-d35bf700-a3c0-11eb-977c-ec2717bbbf47.png)

Getting a 404 error when going to www.hnclone.win

**Comment by clintonwoo** [comment]
Thanks for raising, I moved it to a new Kubernetes cluster I'm using, just fixed it now.

I have a lot of free time nowadays. Feel free to reach out to me on Twitter https://twitter.com/ClintonDAnnolfo if you have anything on your mind.. ping me how you found out about this project? Or what you want to use it for
