### ISSUE TITLE
wrong mention /react-apollo/getting started

### ISSUE THREAD

**Issue by enesinan** [clintonwoo/hackernews-react-graphql#61]
when I follow the this documentation
( https://www.howtographql.com/react-apollo/1-getting-started/  )

 I realise that here to wrong mention 
because after the yarn start it gives to some error 
and after the realise that,
I check it out and I find that`s wrong mention 

should we give to black background color here 
look like that --> import logo from './../logo.svg';

--> import './../styles/App.css';

![ads](https://user-images.githubusercontent.com/72499839/119395864-c8a4c280-bcdc-11eb-97b3-e1fb2dce5a78.png)

**Comment by clintonwoo** [comment]
Hey I think you may be looking for this project: https://github.com/howtographql/react-apollo
