### ISSUE TITLE
Password storage

### ISSUE THREAD

**Issue by rgfoley** [clintonwoo/hackernews-react-graphql#7]
I'm not a security expert, but wouldn't it be advisable to only store the hashed password of a user? My understanding is that the LocalStrategy does not do any hashing for you, so the Cache is holding a plaintext copy of each user's password in memory.

**Comment by devsdmf** [comment]
Idk if I interpreted right the code, but all the data is being saved in the memory ?

**Comment by clintonwoo** [comment]
Password is now hashed using inbuilt Node.js crypto library and pbkdf2
