### ISSUE TITLE
/best path returns inaccurate/NaN results 

### ISSUE THREAD

**Issue by roselpadilla** [clintonwoo/hackernews-react-graphql#8]
<img width="798" alt="screen shot 2017-10-03 at 2 16 06 pm" src="https://user-images.githubusercontent.com/26841025/31141469-80113b16-a845-11e7-8fa2-5f8c2c73837e.png">

**Comment by clintonwoo** [comment]
Thanks. There is currently a pull request in progress fixing this:
https://github.com/clintonwoo/hackernews-react-graphql/pull/9
